const { createApp, ref, reactive, computed, nextTick, onMounted, onBeforeUnmount } = Vue;
const ASSET_ROOT = new URL("../", import.meta.url).href;

const loadJson = path => fetch(new URL(path, ASSET_ROOT)).then(r => { if (!r.ok) throw new Error(path); return r.json(); });
const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
const lerp = (a, b, t) => a + (b - a) * t;
const removeGreenBackground = image => {
  const canvas = document.createElement("canvas");
  canvas.width = image.naturalWidth || image.width;
  canvas.height = image.naturalHeight || image.height;
  const context = canvas.getContext("2d", { willReadFrequently: true });
  context.drawImage(image, 0, 0);
  const pixels = context.getImageData(0, 0, canvas.width, canvas.height);
  const data = pixels.data;
  const visited = new Uint8Array(canvas.width * canvas.height);
  const queue = [];
  const isGreen = offset => data[offset + 1] > 120 && data[offset + 1] > data[offset] * 1.28 && data[offset + 1] > data[offset + 2] * 1.28;
  const enqueue = (x, y) => { const index = y * canvas.width + x; if (!visited[index]) { visited[index] = 1; queue.push(index); } };
  for (let x = 0; x < canvas.width; x++) { enqueue(x, 0); enqueue(x, canvas.height - 1); }
  for (let y = 1; y < canvas.height - 1; y++) { enqueue(0, y); enqueue(canvas.width - 1, y); }
  for (let cursor = 0; cursor < queue.length; cursor++) {
    const index = queue[cursor]; const x = index % canvas.width; const y = Math.floor(index / canvas.width); const offset = index * 4;
    if (!isGreen(offset)) continue;
    data[offset + 3] = 0;
    if (x > 0) enqueue(x - 1, y); if (x < canvas.width - 1) enqueue(x + 1, y); if (y > 0) enqueue(x, y - 1); if (y < canvas.height - 1) enqueue(x, y + 1);
  }
  context.putImageData(pixels, 0, 0);
  return canvas;
};
const loadBlackKeyedImage = (url, threshold = 38) => new Promise((resolve, reject) => { const image = new Image(); image.onload = () => { const canvas = document.createElement("canvas"); canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; const ctx = canvas.getContext("2d"); ctx.drawImage(image, 0, 0); const pixels = ctx.getImageData(0, 0, canvas.width, canvas.height); for (let i = 0; i < pixels.data.length; i += 4) { if (pixels.data[i] < threshold && pixels.data[i + 1] < threshold && pixels.data[i + 2] < threshold) pixels.data[i + 3] = 0; } ctx.putImageData(pixels, 0, 0); resolve(canvas); }; image.onerror = reject; image.src = url; });
const LETTER_ALL_INDEX = { "ko-kai": 0, "cho-chan": 7, "do-chada": 13, "to-patak": 14, "do-dek": 19, "to-tao": 20, "bo-baimai": 25, "po-pla": 26, "o-ang": 42 };
const NON_MIDDLE_CONSONANTS = [
  ["ข",1],["ฃ",2],["ค",3],["ฅ",4],["ฆ",5],["ง",6],["ฉ",8],["ช",9],["ซ",10],["ฌ",11],["ญ",12],["ฐ",15],["ฑ",16],["ฒ",17],["ณ",18],["ถ",21],["ท",22],["ธ",23],["น",24],["ผ",27],["ฝ",28],["พ",29],["ฟ",30],["ภ",31],["ม",32],["ย",33],["ร",34],["ล",35],["ว",36],["ศ",37],["ษ",38],["ส",39],["ห",40],["ฬ",41],["ฮ",43]
].map(([char, spriteIndex]) => ({ id: `consonant-${spriteIndex}`, char, name: "พยัญชนะ", spriteIndex, isMiddleClass: false }));

const THAI_CONSONANT_CLASSES = Object.fromEntries([
  ["\u0e02", "high"], ["\u0e03", "high"], ["\u0e09", "high"], ["\u0e10", "high"], ["\u0e16", "high"], ["\u0e1c", "high"], ["\u0e1d", "high"], ["\u0e28", "high"], ["\u0e29", "high"], ["\u0e2a", "high"], ["\u0e2b", "high"],
  ["\u0e01", "middle"], ["\u0e08", "middle"], ["\u0e0e", "middle"], ["\u0e0f", "middle"], ["\u0e14", "middle"], ["\u0e15", "middle"], ["\u0e1a", "middle"], ["\u0e1b", "middle"], ["\u0e2d", "middle"],
  ["\u0e04", "low"], ["\u0e05", "low"], ["\u0e06", "low"], ["\u0e07", "low"], ["\u0e0a", "low"], ["\u0e0b", "low"], ["\u0e0c", "low"], ["\u0e0d", "low"], ["\u0e11", "low"], ["\u0e12", "low"], ["\u0e13", "low"], ["\u0e17", "low"], ["\u0e18", "low"], ["\u0e19", "low"], ["\u0e1e", "low"], ["\u0e1f", "low"], ["\u0e20", "low"], ["\u0e21", "low"], ["\u0e22", "low"], ["\u0e23", "low"], ["\u0e25", "low"], ["\u0e27", "low"], ["\u0e2c", "low"], ["\u0e2e", "low"]
]);
const consonantClass = char => THAI_CONSONANT_CLASSES[char] || "low";
NON_MIDDLE_CONSONANTS.forEach(letter => { letter.thaiClass = consonantClass(letter.char); });

class AudioManager {
  constructor() { this.context = null; this.master = null; this.compressor = null; this.musicGain = null; this.sfxGain = null; this.musicLevel = .84; this.muted = false; this.musicPlaying = false; this.musicTimer = null; this.noteIndex = 0; this.voices = []; }
  ensureContext() { if (!this.context) { this.context = new (window.AudioContext || window.webkitAudioContext)(); this.master = this.context.createGain(); this.compressor = this.context.createDynamicsCompressor(); this.musicGain = this.context.createGain(); this.sfxGain = this.context.createGain(); this.musicGain.gain.value = this.musicLevel; this.sfxGain.gain.value = .36; this.musicGain.connect(this.master); this.sfxGain.connect(this.master); this.master.connect(this.compressor); this.compressor.threshold.value = -18; this.compressor.knee.value = 20; this.compressor.ratio.value = 4; this.compressor.attack.value = .003; this.compressor.release.value = .25; this.compressor.connect(this.context.destination); this.master.gain.value = this.muted ? 0 : 1; } if (this.context.state === "suspended") this.context.resume(); }
  setMusicVolume(value) { this.musicLevel = clamp(Number(value), 0, 1) * .84; if (this.musicGain && this.context) this.musicGain.gain.setTargetAtTime(this.musicLevel, this.context.currentTime, .04); }
  setMuted(muted) { this.muted = muted; if (this.master) this.master.gain.value = muted ? 0 : 1; }
  tone(frequency, duration = .2, type = "sine", volume = .18, destination = this.sfxGain, delay = 0) { if (this.muted) return; this.ensureContext(); const now = this.context.currentTime + delay; const oscillator = this.context.createOscillator(), gain = this.context.createGain(); oscillator.type = type; oscillator.frequency.setValueAtTime(frequency, now); gain.gain.setValueAtTime(.0001, now); gain.gain.exponentialRampToValueAtTime(volume, now + .025); gain.gain.exponentialRampToValueAtTime(.0001, now + duration); oscillator.connect(gain); gain.connect(destination); oscillator.start(now); oscillator.stop(now + duration + .04); }
  startMusic() { if (this.musicPlaying) return; this.ensureContext(); this.musicPlaying = true; this.noteIndex = 0; this.scheduleNote(); }
  scheduleNote() { if (!this.musicPlaying) return; const notes = [523.25, 659.25, 783.99, 659.25, 587.33, 698.46, 880, 698.46]; const note = notes[this.noteIndex++ % notes.length]; this.tone(note, .7, "sine", .18, this.musicGain); if (this.noteIndex % 4 === 1) this.tone(note / 2, 1.3, "triangle", .08, this.musicGain, .03); this.musicTimer = window.setTimeout(() => this.scheduleNote(), 760); }
  stopMusic() { this.musicPlaying = false; if (this.musicTimer) window.clearTimeout(this.musicTimer); this.musicTimer = null; }
  correct() { this.tone(659.25, .13, "sine", .22); this.tone(783.99, .16, "sine", .2, this.sfxGain, .1); this.tone(1046.5, .24, "sine", .18, this.sfxGain, .22); }
  wrong() { this.tone(220, .16, "triangle", .12); this.tone(185, .22, "triangle", .1, this.sfxGain, .12); }
  collect() { this.tone(880, .12, "sine", .14); }
  start() { this.tone(392, .12, "sine", .12); this.tone(523.25, .16, "sine", .14, this.sfxGain, .11); this.tone(659.25, .24, "sine", .16, this.sfxGain, .24); }
  target() { this.tone(587.33, .12, "sine", .08); this.tone(783.99, .2, "sine", .1, this.sfxGain, .1); }
  magic() { [523.25, 659.25, 783.99, 1046.5].forEach((n, i) => this.tone(n, .3, "sine", .1, this.sfxGain, i * .07)); }
  arReady() { this.tone(392, .16, "triangle", .1); this.tone(587.33, .22, "sine", .13, this.sfxGain, .12); this.tone(880, .3, "sine", .16, this.sfxGain, .25); }
  wind() { this.tone(330, .6, "sine", .025, this.musicGain); }
  speak() {}
}

class Vector2 {
  constructor(x = 0, y = 0) { this.x = x; this.y = y; }
  add(v) { this.x += v.x; this.y += v.y; return this; }
  scale(n) { this.x *= n; this.y *= n; return this; }
  clone() { return new Vector2(this.x, this.y); }
  distanceTo(v) { return Math.hypot(this.x - v.x, this.y - v.y); }
}

class WindField {
  constructor() { this.current = new Vector2(.006, .002); this.target = new Vector2(.006, .002); this.timer = 0; this.state = "calm"; this.strength = .35; this.gust = 1; }
  update(dt) {
    this.timer -= dt;
    if (this.timer <= 0) { const roll = Math.random(); this.state = roll < .34 ? "calm" : roll < .86 ? "breeze" : "gust"; this.timer = this.state === "gust" ? 650 + Math.random() * 1450 : 1800 + Math.random() * 6500; this.strength = this.state === "calm" ? .18 + Math.random() * .18 : this.state === "breeze" ? .42 + Math.random() * .38 : 1.1 + Math.random() * .9; const direction = Math.random() < .5 ? -1 : 1; this.target = new Vector2(direction * this.strength * (.012 + Math.random() * .018), (Math.random() - .5) * .012 * this.strength); this.gust = this.state === "gust" ? 1.7 : .75 + Math.random() * .45; }
    const t = 1 - Math.pow(.001, dt / 1000);
    this.current.x = lerp(this.current.x, this.target.x, t); this.current.y = lerp(this.current.y, this.target.y, t); this.gust = lerp(this.gust, 1, dt / 1000);
  }
  sample(position, time) { return new Vector2(this.current.x * this.gust + Math.sin(time * .001 + position.y * .01) * .004, this.current.y + Math.cos(time * .0014 + position.x * .01) * .002); }
}

class ParticleSystem {
  constructor() { this.items = []; }
  burst(x, y, amount = 10, colorA = "#fff19a", colorB = "#fff") { for (let i = 0; i < amount; i++) this.items.push({ x, y, vx: (Math.random() - .5) * 1.2, vy: -.35 - Math.random() * .8, size: 14 + Math.random() * 16, life: 1, color: i % 2 ? colorA : colorB, text: i % 3 ? "✦" : "•" }); }
  update(dt) { this.items.forEach(p => { p.x += p.vx * dt; p.y += p.vy * dt; p.vy += .001 * dt; p.life -= dt * .001; }); this.items = this.items.filter(p => p.life > 0); }
  draw(ctx) { this.items.forEach(p => { ctx.save(); ctx.globalAlpha = p.life; ctx.fillStyle = p.color; ctx.font = `${p.size}px Arial`; ctx.fillText(p.text, p.x, p.y); ctx.restore(); }); }
}

class FloatingMushroom {
  constructor(letter, index, x, y) { this.letter = letter; this.spriteIndex = LETTER_ALL_INDEX[letter.id] ?? letter.spriteIndex; this.position = new Vector2(x, y); this.home = this.position.clone(); this.phase = Math.random() * Math.PI * 2; this.speed = .7 + Math.random() * .6; this.pulseSpeed = .0015 + Math.random() * .002; this.pulseAmount = .055 + Math.random() * .04; this.glowColor = ["125,255,218", "255,224,118", "204,148,255", "124,212,255", "255,151,205"][Math.floor(Math.random() * 5)]; this.radius = 69; this.index = index; this.collected = false; this.wrongPulse = 0; this.hover = 0; }
  update(dt, time, wind, width, height, target) {
    if (this.collected) return;
    const breeze = wind.sample(this.position, time); const wave = new Vector2(Math.sin(time * .001 * this.speed + this.phase) * .012, Math.cos(time * .0013 * this.speed + this.phase) * .008);
    const targetBias = target ? .0008 : 0;
    this.position.x += (breeze.x + wave.x + targetBias) * dt; this.position.y += (breeze.y + wave.y) * dt;
    this.position.x += (this.home.x - this.position.x) * .00045 * dt; this.position.y += (this.home.y - this.position.y) * .00045 * dt;
    this.position.x = clamp(this.position.x, 82, width - 82); this.position.y = clamp(this.position.y, 115, height - 105);
    this.wrongPulse = Math.max(0, this.wrongPulse - dt); this.hover = lerp(this.hover, target ? 1 : 0, .1);
  }
  hitTest(point) { return !this.collected && this.position.distanceTo(point) < this.radius; }
  draw(ctx, image, spriteRect, time, isTarget) {
    if (this.collected) return;
    const bob = Math.sin(time * .002 * this.speed + this.phase) * 5 - this.hover * 4; const rect = spriteRect(this.spriteIndex);
    ctx.save(); ctx.translate(this.position.x, this.position.y + bob); ctx.globalAlpha = 1; if (this.wrongPulse) ctx.rotate(Math.sin(time * .04) * .07);
    const pulseWave = (Math.sin(time * this.pulseSpeed + this.phase) + 1) / 2; const grow = 1 + (pulseWave - .5) * this.pulseAmount; const size = (isTarget ? 154 : 144) * grow; const glowSize = size * (0.76 + pulseWave * .18);
    const aura = ctx.createRadialGradient(0, 0, size * .08, 0, 0, glowSize); aura.addColorStop(0, `rgba(${this.glowColor},${.18 + pulseWave * .18})`); aura.addColorStop(.52, `rgba(${this.glowColor},${.11 + pulseWave * .1})`); aura.addColorStop(1, `rgba(${this.glowColor},0)`);
    ctx.save(); ctx.globalCompositeOperation = "lighter"; ctx.fillStyle = aura; ctx.beginPath(); ctx.arc(0, 0, glowSize, 0, Math.PI * 2); ctx.fill(); ctx.restore();
    ctx.shadowColor = `rgba(${this.glowColor},${.48 + pulseWave * .3})`; ctx.shadowBlur = 15 + pulseWave * 18; ctx.shadowOffsetY = 9; ctx.drawImage(image, rect.sx, rect.sy, rect.sw, rect.sh, -size / 2, -size / 2, size, size); ctx.restore();
  }
}

class HeroGuide {
  constructor() { this.state = "idle"; this.timer = 0; this.frames = { idle: { x: 418, y: 836 }, cheer: { x: 418, y: 0 }, sad: { x: 836, y: 0 }, excited: { x: 0, y: 418 }, wave: { x: 0, y: 0 } }; }
  setState(name, duration = 1300) { this.state = this.frames[name] ? name : "idle"; this.timer = duration; }
  update(dt) { if (this.timer > 0) { this.timer -= dt; if (this.timer <= 0) this.state = "idle"; } }
  frameStyle() { const f = this.frames[this.state] || this.frames.idle; return { backgroundPosition: `-${f.x}px -${f.y}px` }; }
}

class GardenGame {
  constructor(canvas, assets, callbacks) { this.canvas = canvas; this.ctx = canvas.getContext("2d"); this.assets = assets; this.callbacks = callbacks; this.width = canvas.width; this.height = canvas.height; this.wind = new WindField(); this.particles = new ParticleSystem(); this.items = []; this.targetChar = ""; this.targetClass = "middle"; this.running = false; this.completed = false; this.last = 0; this.raf = 0; this.toast = ""; this.toastUntil = 0; this.celebrationRing = null; }
  spriteRect(index) { const meta = this.assets.meta; if (meta.frames?.[index]) return meta.frames[index]; const w = meta.sourceWidth / meta.columns, h = meta.sourceHeight / meta.rows; return { sx: (index % meta.columns) * w, sy: Math.floor(index / meta.columns) * h, sw: w, sh: h }; }
  start(letters, targetChar, maxCount = 10, targetClass = "middle") { this.items = []; this.completed = false; this.targetClass = targetClass; const source = [...new Map([...letters, ...NON_MIDDLE_CONSONANTS].map(letter => [letter.id, letter])).values()]; const targets = source.filter(letter => targetClass === "all" || letter.thaiClass === targetClass); const count = Math.min(source.length, Math.max(5, Math.min(10, Number(maxCount) || 10))); const chosen = []; if (targets.length) chosen.push(targets[Math.floor(Math.random() * targets.length)]); const remaining = source.filter(letter => !chosen.some(item => item.id === letter.id)); while (chosen.length < count && remaining.length) { chosen.push(remaining.splice(Math.floor(Math.random() * remaining.length), 1)[0]); } const shuffled = chosen.sort(() => Math.random() - .5); shuffled.forEach((letter, i) => { let x, y, attempts = 0; do { x = 105 + Math.random() * 750; y = 135 + Math.random() * 345; attempts++; } while (this.items.some(item => item.position.distanceTo(new Vector2(x, y)) < 112) && attempts < 60); this.items.push(new FloatingMushroom(letter, i, x, y)); }); this.targetChar = targetChar; this.running = true; this.last = performance.now(); this.raf = requestAnimationFrame(t => this.loop(t)); }
  setTarget(char) { this.targetChar = char; }
  loop(time) { if (!this.running) return; const dt = Math.min(34, time - this.last || 16); this.last = time; this.wind.update(dt); this.items.forEach(item => item.update(dt, time, this.wind, this.width, this.height, false)); this.particles.update(dt); if (this.celebrationRing) { this.celebrationRing.life -= dt * .001; this.celebrationRing.rotation += dt * .0008; if (this.celebrationRing.life <= 0) this.celebrationRing = null; } this.draw(time); this.raf = requestAnimationFrame(t => this.loop(t)); }
  drawCover(image) { const scale = Math.max(this.width / image.width, this.height / image.height); const w = image.width * scale, h = image.height * scale; this.ctx.drawImage(image, (this.width - w) / 2, (this.height - h) / 2, w, h); }
  draw(time) {
    const ctx = this.ctx; ctx.clearRect(0, 0, this.width, this.height); if (this.assets.background.complete && this.assets.background.naturalWidth) { this.drawCover(this.assets.background); ctx.fillStyle = "rgba(5,28,72,.18)"; ctx.fillRect(0, 0, this.width, this.height); } else { ctx.fillStyle = "#1b4f91"; ctx.fillRect(0, 0, this.width, this.height); }
    if (this.assets.foreground.complete && this.assets.foreground.naturalWidth) { ctx.save(); ctx.globalAlpha = .94; this.drawCover(this.assets.foreground); ctx.restore(); }
    ctx.fillStyle = "rgba(15,37,91,.62)"; ctx.roundRect(22, 16, 390, 56, 18); ctx.fill(); ctx.fillStyle = "#ffe777"; ctx.font = "800 25px 'Noto Sans Thai'"; ctx.fillText("สวนเห็ดมหัศจรรย์", 42, 43); ctx.fillStyle = "#d7f8ff"; ctx.font = "600 14px 'Noto Sans Thai'"; ctx.fillText("หาอักษรกลางให้ตรงกับโจทย์", 42, 63);
    [...this.items].sort((a, b) => a.position.y - b.position.y).forEach(item => item.draw(ctx, this.assets.letters, () => this.spriteRect(item.spriteIndex), time, false)); this.particles.draw(ctx);
    if (this.celebrationRing && this.assets.magicRing.complete && this.assets.magicRing.naturalWidth) { const ring = this.celebrationRing; ctx.save(); ctx.globalAlpha = Math.max(0, ring.life) * .9; ctx.translate(ring.x, ring.y); ctx.rotate(ring.rotation); const size = 204 + (1 - ring.life) * 70; ctx.drawImage(this.assets.magicRing, -size / 2, -size / 2, size, size); ctx.restore(); }
    if (this.toast && Date.now() < this.toastUntil) { ctx.fillStyle = "rgba(14,35,76,.86)"; ctx.roundRect(320, 535, 320, 42, 21); ctx.fill(); ctx.fillStyle = "#fff"; ctx.font = "700 19px 'Noto Sans Thai'"; ctx.textAlign = "center"; ctx.fillText(this.toast, 480, 563); ctx.textAlign = "left"; }
  }
  pointerPoint(event) { const rect = this.canvas.getBoundingClientRect(); return new Vector2(clamp((event.clientX - rect.left) / rect.width * this.width, 0, this.width), clamp((event.clientY - rect.top) / rect.height * this.height, 0, this.height)); }
  select(point) { if (this.completed) return; const candidates = this.items.filter(item => item.hitTest(point)).sort((a, b) => b.position.y - a.position.y); const item = candidates[0]; if (!item) return; const isCorrectClass = this.targetClass === "all" || item.letter.thaiClass === this.targetClass; if (isCorrectClass) { item.collected = true; this.celebrationRing = { x: item.position.x, y: item.position.y, life: 1, rotation: 0 }; this.particles.burst(item.position.x, item.position.y, 12); this.toast = `เก่งมาก! นี่คือ ${item.letter.char} ${item.letter.name}`; this.toastUntil = Date.now() + 1400; this.callbacks.correct(item); } else { item.wrongPulse = 550; this.toast = `ลองใหม่ เห็ดนี้อยู่นอกหมวดที่เลือก`; this.toastUntil = Date.now() + 1500; this.callbacks.wrong(item); } }
  stop() { this.running = false; cancelAnimationFrame(this.raf); }
}

const PROGRESS_KEY = "middle-class-progression";
function readProgression() { try { const saved = JSON.parse(localStorage.getItem(PROGRESS_KEY) || "null"); return { stars: Number(saved?.stars) || 0, unlockedLetters: Array.isArray(saved?.unlockedLetters) ? saved.unlockedLetters : [], completedRounds: Number(saved?.completedRounds) || 0, bestScore: Number(saved?.bestScore) || 0, highestLevel: Math.max(0, Number(saved?.highestLevel) || 0) }; } catch (e) { return { stars: 0, unlockedLetters: [], completedRounds: 0, bestScore: 0, highestLevel: 0 }; } }

const app = createApp({ setup() {
  const mistakes = ref(0), roundStars = ref(0), progression = ref(readProgression());
  const levels = ref([]), activeLevelIndex = ref(0), levelLetters = ref([]);
  const screen = ref("home"), showCollection = ref(false), soundOn = ref(true), musicVolume = ref(Number(localStorage.getItem("middle-class-music-volume") || .55)), arOn = ref(false), score = ref(Number(localStorage.getItem("middle-class-score") || 0)), lives = ref(5), letters = ref([]), sprites = ref(null), target = ref({ char: "ก", name: "ไก่" }), collected = ref(0), gameCanvas = ref(null), cameraVideo = ref(null), pointer = ref({ x: 480, y: 300 }), heroState = ref("idle");
  const game = ref(null); const audio = new AudioManager(); const arError = ref(""); const SESSION_SECONDS = 120; const sessionTime = ref(SESSION_SECONDS), waveNumber = ref(0), waveCleared = ref(0), waveMiddleTotal = ref(0), waveMiddleCollected = ref(0), combo = ref(0), bestCombo = ref(0); let sessionTimer = null, waveTimer = null; const cameraState = { stream: null, landmarker: null, busy: false, hoverId: null, hoverStartedAt: 0, hoverSelected: false };
  const progress = computed(() => Math.round(collected.value / (letters.value.length || 9) * 100)); const pointerStyle = computed(() => ({ left: `${pointer.value.x / 960 * 100}%`, top: `${pointer.value.y / 600 * 100}%` })); const heroSpriteStyle = computed(() => ({ width: "418px", height: "418px", backgroundImage: `url('${new URL("assets/sprites/hero-o.png", ASSET_ROOT).href}')`, backgroundSize: "1254px 1254px", backgroundPosition: "-836px -836px", backgroundRepeat: "no-repeat" })); const guideFrames = { idle: { x: 418, y: 836 }, cheer: { x: 418, y: 0 }, sad: { x: 836, y: 0 }, excited: { x: 0, y: 418 }, wave: { x: 0, y: 0 } }; const heroGuideStyle = computed(() => { const f = guideFrames[heroState.value] || guideFrames.idle; return { backgroundPosition: `-${f.x}px -${f.y}px` }; });
  const settingsOpen = ref(false); const settings = reactive({ category: localStorage.getItem("middle-class-category") || "middle", time: Number(localStorage.getItem("middle-class-time") || 120), hearts: Number(localStorage.getItem("middle-class-hearts") || 5), mushrooms: Number(localStorage.getItem("middle-class-mushrooms") || 10), difficulty: localStorage.getItem("middle-class-difficulty") || "normal", reducedMotion: localStorage.getItem("middle-class-reduced-motion") === "true" });
  const assets = { letters: new Image(), background: new Image(), foreground: new Image(), magicRing: new Image() };
  const unlockedCount = computed(() => progression.value.unlockedLetters.length);
  const activeLevel = computed(() => levels.value[activeLevelIndex.value] || null); const levelProgress = computed(() => Math.round(waveMiddleCollected.value / (waveMiddleTotal.value || 1) * 100)); const timerProgress = computed(() => Math.max(0, Math.round(sessionTime.value / settings.time * 100))); const levelUnlocked = index => index <= progression.value.highestLevel;
  function saveProgression() { localStorage.setItem(PROGRESS_KEY, JSON.stringify(progression.value)); }
  const selectedPool = () => [...letters.value, ...NON_MIDDLE_CONSONANTS].filter(letter => letter.thaiClass === settings.category);
  const categoryLabel = computed(() => settings.category === "all" ? "ทบทวน 3 หมู่" : settings.category === "high" ? "อักษรสูง" : settings.category === "low" ? "อักษรต่ำ" : "อักษรกลาง");
  const categoryMission = computed(() => settings.category === "all" ? "หาอักษรให้ตรงกับหมวดที่เลือก" : `หา${categoryLabel.value}ให้ตรงกับโจทย์`);
  const displayLetters = computed(() => settings.category === "all" ? [...letters.value, ...NON_MIDDLE_CONSONANTS] : selectedPool());
  function isLetterUnlocked(letter) { return progression.value.unlockedLetters.includes(letter.id); }
  function unlockLetter(letter) { if (!isLetterUnlocked(letter)) { progression.value.unlockedLetters = [...progression.value.unlockedLetters, letter.id]; saveProgression(); } }
  function sampleRoundLetters(pool) {
    const source = [...new Map(pool.map(letter => [letter.id, letter])).values()];
    if (!source.length) return [];
    const middle = source.filter(letter => letter.isMiddleClass);
    const count = Math.min(source.length, 5 + Math.floor(Math.random() * 6));
    const chosen = [];
    const addRandom = candidates => {
      const remaining = candidates.filter(letter => !chosen.some(item => item.id === letter.id));
      while (chosen.length < count && remaining.length) {
        const index = Math.floor(Math.random() * remaining.length);
        chosen.push(remaining.splice(index, 1)[0]);
      }
    };
    if (middle.length) chosen.push(middle[Math.floor(Math.random() * middle.length)]);
    addRandom(source);
    return chosen.sort(() => Math.random() - .5);
  }
  function chooseTarget() { const availableItems = game.value?.items.filter(item => !item.collected && item.letter.isMiddleClass) || []; if (!availableItems.length) return; const selectedItem = availableItems[Math.floor(Math.random() * availableItems.length)]; target.value = selectedItem.letter; game.value.setTarget(target.value.char); heroState.value = "wave"; audio.target(); audio.speak(`หาอักษรกลาง ${target.value.char} ${target.value.name}`); }
  async function startGame() { screen.value = "game"; lives.value = 3; collected.value = 0; score.value = 0; heroState.value = "wave"; audio.startMusic(); audio.start(); window.scrollTo({ top: 0, left: 0, behavior: "instant" }); document.documentElement.scrollTop = 0; document.body.scrollTop = 0; await nextTick(); if (!gameCanvas.value || !sprites.value) return; game.value?.stop(); game.value = new GardenGame(gameCanvas.value, { letters: assets.letters, background: assets.background, foreground: assets.foreground, magicRing: assets.magicRing, meta: sprites.value.sheets.letters }, { correct: handleCorrect, wrong: handleWrong }); game.value.start(letters.value, target.value.char); chooseTarget(); }
  function handleCorrect(item) { collected.value++; score.value += 10; localStorage.setItem("middle-class-score", score.value); heroState.value = "cheer"; audio.correct(); audio.collect(); audio.magic(); audio.speak(`${item.letter.char} ${item.letter.name} เก่งมาก`); if (collected.value >= letters.value.length) { game.value.completed = true; heroState.value = "excited"; game.value.toast = "ภารกิจสำเร็จ!"; game.value.toastUntil = Date.now() + 2600; audio.speak("ภารกิจสำเร็จ เก่งมาก"); window.setTimeout(() => { game.value?.stop(); audio.stopMusic(); screen.value = "result"; }, 1800); } else setTimeout(chooseTarget, 500); }
  function handleWrong() { lives.value--; heroState.value = "sad"; audio.wrong(); audio.speak(`ลองใหม่ อ่านอักษรบนเห็ดอีกครั้งนะ`); if (lives.value <= 0) { setTimeout(() => { lives.value = 3; collected.value = 0; game.value?.start(letters.value, target.value.char); heroState.value = "idle"; }, 1200); } }
  async function startGame() { screen.value = "game"; lives.value = 3; mistakes.value = 0; roundStars.value = 0; collected.value = 0; heroState.value = "wave"; audio.startMusic(); audio.start(); window.scrollTo({ top: 0, left: 0, behavior: "instant" }); document.documentElement.scrollTop = 0; document.body.scrollTop = 0; await nextTick(); if (!gameCanvas.value || !sprites.value) return; game.value?.stop(); game.value = new GardenGame(gameCanvas.value, { letters: assets.letters, background: assets.background, foreground: assets.foreground, magicRing: assets.magicRing, meta: sprites.value.sheets.letters }, { correct: handleCorrect, wrong: handleWrong }); game.value.start(letters.value, target.value.char); chooseTarget(); }
  function handleCorrect(item) { collected.value++; score.value += 10; unlockLetter(item.letter); localStorage.setItem("middle-class-score", score.value); heroState.value = "cheer"; audio.correct(); audio.collect(); audio.magic(); if (collected.value >= letters.value.length) { game.value.completed = true; roundStars.value = mistakes.value === 0 ? 3 : mistakes.value <= 2 ? 2 : 1; progression.value = { ...progression.value, stars: progression.value.stars + roundStars.value, completedRounds: progression.value.completedRounds + 1, bestScore: Math.max(progression.value.bestScore, score.value) }; saveProgression(); heroState.value = "excited"; game.value.toast = `Stars +${roundStars.value}`; game.value.toastUntil = Date.now() + 2600; window.setTimeout(() => { game.value?.stop(); audio.stopMusic(); screen.value = "result"; }, 1800); } else setTimeout(chooseTarget, 500); }
  function handleWrong() { mistakes.value++; lives.value--; heroState.value = "sad"; audio.wrong(); if (lives.value <= 0) { setTimeout(() => { lives.value = 3; collected.value = 0; game.value?.start(letters.value, target.value.char); heroState.value = "idle"; }, 1200); } }
  function setLevel(index) { if (!levels.value.length) levels.value = [{ id: "gate-garden", number: 1, title: "Level 1", description: "Learn middle-class consonants", letterIds: ["ko-kai", "cho-chan", "do-dek"] }, { id: "crystal-garden", number: 2, title: "Level 2", description: "Find more letters", letterIds: ["ko-kai", "cho-chan", "do-dek", "to-tao", "bo-baimai", "po-pla"] }, { id: "royal-hall", number: 3, title: "Level 3", description: "Find all middle-class letters", letterIds: ["ko-kai", "cho-chan", "do-chada", "to-patak", "do-dek", "to-tao", "bo-baimai", "po-pla", "o-ang"] }]; const selected = levels.value[index]; if (!selected || !levelUnlocked(index)) return false; activeLevelIndex.value = index; const ids = new Set(selected.letterIds || []); levelLetters.value = letters.value.filter(letter => ids.has(letter.id)); return levelLetters.value.length > 0; }
  async function startGame(levelIndex = activeLevelIndex.value) { if (!letters.value.length) { const letterData = await loadJson("data/letters.json"); letters.value = letterData.letters || []; } if (!setLevel(levelIndex)) { levelLetters.value = letters.value.slice(0, 3); } if (!levelLetters.value.length) return; clearSessionTimers(); screen.value = "game"; lives.value = 5; mistakes.value = 0; roundStars.value = 0; score.value = 0; collected.value = 0; sessionTime.value = SESSION_SECONDS; waveNumber.value = 0; waveCleared.value = 0; waveMiddleTotal.value = 0; waveMiddleCollected.value = 0; combo.value = 0; bestCombo.value = 0; heroState.value = "wave"; audio.startMusic(); audio.start(); window.scrollTo({ top: 0, left: 0, behavior: "instant" }); document.documentElement.scrollTop = 0; document.body.scrollTop = 0; await nextTick(); if (!gameCanvas.value || !sprites.value) return; game.value?.stop(); game.value = new GardenGame(gameCanvas.value, { letters: assets.letters, background: assets.background, foreground: assets.foreground, magicRing: assets.magicRing, meta: sprites.value.sheets.letters }, { correct: handleCorrect, wrong: handleWrong }); startWave(); sessionTimer = window.setInterval(() => { if (sessionTime.value <= 1) { sessionTime.value = 0; finishSession(); } else sessionTime.value--; }, 1000); }
  function handleCorrect(item) { collected.value++; waveMiddleCollected.value++; combo.value++; bestCombo.value = Math.max(bestCombo.value, combo.value); score.value += 10 + Math.min(combo.value - 1, 4) * 2; if (item.letter.isMiddleClass) unlockLetter(item.letter); localStorage.setItem("middle-class-score", score.value); heroState.value = "cheer"; audio.correct(); audio.collect(); audio.magic(); const remainingMiddle = game.value?.items.filter(gameItem => gameItem.letter.isMiddleClass && !gameItem.collected).length || 0; if (remainingMiddle === 0) finishWave(); else setTimeout(chooseTarget, 450); }
  function handleWrong() { mistakes.value++; lives.value--; combo.value = 0; heroState.value = "sad"; audio.wrong(); if (lives.value <= 0) { window.setTimeout(() => { lives.value = 5; waveMiddleCollected.value = 0; startWave(); heroState.value = "idle"; }, 1200); } }
  function clearSessionTimers() { if (sessionTimer) window.clearInterval(sessionTimer); if (waveTimer) window.clearTimeout(waveTimer); sessionTimer = null; waveTimer = null; }
  function startWave() { if (!game.value || sessionTime.value <= 0) return; waveNumber.value++; waveMiddleCollected.value = 0; game.value.start(levelLetters.value, target.value.char); waveMiddleTotal.value = game.value.items.filter(item => item.letter.isMiddleClass).length; game.value.toast = `ชุดที่ ${waveNumber.value} เริ่มแล้ว!`; game.value.toastUntil = Date.now() + 1500; chooseTarget(); }
  function finishWave() { game.value.completed = true; waveCleared.value++; combo.value++; bestCombo.value = Math.max(bestCombo.value, combo.value); const bonus = 25 + Math.min(combo.value, 5) * 5; score.value += bonus; localStorage.setItem("middle-class-score", score.value); game.value.toast = `เคลียร์ชุดที่ ${waveNumber.value}! โบนัส +${bonus}`; game.value.toastUntil = Date.now() + 1800; heroState.value = "excited"; waveTimer = window.setTimeout(() => { waveTimer = null; startWave(); }, 900); }
  function finishSession() { if (screen.value !== "game") return; clearSessionTimers(); game.value?.stop(); audio.stopMusic(); roundStars.value = waveCleared.value >= 5 && mistakes.value <= 2 ? 3 : waveCleared.value >= 2 ? 2 : 1; progression.value = { ...progression.value, stars: progression.value.stars + roundStars.value, completedRounds: progression.value.completedRounds + 1, bestScore: Math.max(progression.value.bestScore, score.value) }; saveProgression(); heroState.value = "excited"; screen.value = "result"; }
  function nextLevel() { if (activeLevelIndex.value < levels.value.length - 1) startGame(activeLevelIndex.value + 1); else goHome(); }
  function onPointerMove(e) { if (!game.value) return; pointer.value = game.value.pointerPoint(e); }
  function onPointerDown(e) { if (!game.value) return; pointer.value = game.value.pointerPoint(e); game.value.select(pointer.value); }
  function goHome() { clearSessionTimers(); game.value?.stop(); audio.stopMusic(); stopAR(); screen.value = "home"; window.scrollTo({ top: 0, left: 0, behavior: "instant" }); document.documentElement.scrollTop = 0; document.body.scrollTop = 0; }
  function toggleSound() { soundOn.value = !soundOn.value; audio.setMuted(!soundOn.value); if (!soundOn.value) window.speechSynthesis?.cancel(); }
  function setMusicVolume(event) { musicVolume.value = Number(event.target.value); localStorage.setItem("middle-class-music-volume", String(musicVolume.value)); audio.setMusicVolume(musicVolume.value); }
  async function loadScript(src) { return new Promise((resolve, reject) => { const s = document.createElement("script"); s.src = src; s.crossOrigin = "anonymous"; s.onload = () => { if (window.Vision && !window.MediaPipeTasksVision) window.MediaPipeTasksVision = window.Vision; resolve(); }; s.onerror = () => reject(new Error(`SCRIPT_LOAD_FAILED: ${src}`)); document.head.appendChild(s); }); }
  async function toggleAR() { if (arOn.value) { stopAR(); return; } arError.value = "กำลังเปิดกล้องและระบบ AR..."; try { if (!window.isSecureContext || !navigator.mediaDevices?.getUserMedia) throw new Error("SECURE_CONTEXT_REQUIRED"); if (!window.MediaPipeTasksVision) await loadScript("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/vision_bundle.js"); const { FilesetResolver, HandLandmarker } = window.MediaPipeTasksVision || {}; if (!FilesetResolver || !HandLandmarker) throw new Error("MEDIAPIPE_BUNDLE_UNAVAILABLE"); cameraState.stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user", width: { ideal: 640 }, height: { ideal: 480 } }, audio: false }); cameraVideo.value.srcObject = cameraState.stream; await cameraVideo.value.play(); const vision = await FilesetResolver.forVisionTasks("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm"); const modelAssetPath = "https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task"; try { cameraState.landmarker = await HandLandmarker.createFromOptions(vision, { baseOptions: { modelAssetPath, delegate: "GPU" }, runningMode: "VIDEO", numHands: 1, minHandDetectionConfidence: .55, minTrackingConfidence: .55 }); } catch (gpuError) { console.warn("GPU delegate failed, using CPU", gpuError); cameraState.landmarker = await HandLandmarker.createFromOptions(vision, { baseOptions: { modelAssetPath }, runningMode: "VIDEO", numHands: 1, minHandDetectionConfidence: .55, minTrackingConfidence: .55 }); } arError.value = "ชี้นิ้วค้างบนเห็ดประมาณ 0.5 วินาทีเพื่อเลือก"; arOn.value = true; audio.arReady(); requestAnimationFrame(readHand); } catch (e) { console.warn("AR initialization failed", e); const code = e?.name || e?.message || "UNKNOWN_ERROR"; const messages = { NotAllowedError: "เบราว์เซอร์ไม่อนุญาตกล้อง: กดไอคอนกล้องข้าง URL แล้วเลือก Allow", NotFoundError: "ไม่พบกล้องในอุปกรณ์นี้", NotReadableError: "กล้องกำลังถูกใช้งานโดยโปรแกรมอื่น", SECURE_CONTEXT_REQUIRED: "ต้องเปิดผ่าน http://localhost หรือ HTTPS", MEDIAPIPE_BUNDLE_UNAVAILABLE: "โหลด MediaPipe ไม่สำเร็จ: ตรวจสอบอินเทอร์เน็ตและ CDN" }; arError.value = `${messages[code] || `AR error: ${code}`} `; game.value && (game.value.toast = "ใช้การแตะหน้าจอแทนได้เลย", game.value.toastUntil = Date.now() + 2600); stopAR(false); } }
  async function toggleAR() { if (arOn.value) { stopAR(); return; } arError.value = "กำลังเปิดกล้องและระบบ AR..."; try { if (!window.isSecureContext || !navigator.mediaDevices?.getUserMedia) throw new Error("SECURE_CONTEXT_REQUIRED"); if (!window.MediaPipeTasksVision) await loadScript("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/vision_bundle.js"); const { FilesetResolver, HandLandmarker } = window.MediaPipeTasksVision || {}; if (!FilesetResolver || !HandLandmarker) throw new Error("MEDIAPIPE_BUNDLE_UNAVAILABLE"); cameraState.stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user", width: { ideal: 640 }, height: { ideal: 480 } }, audio: false }); cameraVideo.value.srcObject = cameraState.stream; await cameraVideo.value.play(); const vision = await FilesetResolver.forVisionTasks("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/wasm"); const modelAssetPath = "https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task"; try { cameraState.landmarker = await HandLandmarker.createFromOptions(vision, { baseOptions: { modelAssetPath, delegate: "GPU" }, runningMode: "VIDEO", numHands: 1, minHandDetectionConfidence: .55, minTrackingConfidence: .55 }); } catch (gpuError) { console.warn("GPU delegate failed, using CPU", gpuError); cameraState.landmarker = await HandLandmarker.createFromOptions(vision, { baseOptions: { modelAssetPath }, runningMode: "VIDEO", numHands: 1, minHandDetectionConfidence: .55, minTrackingConfidence: .55 }); } arError.value = "ชี้นิ้วค้างบนเห็ดประมาณ 0.5 วินาทีเพื่อเลือก"; arOn.value = true; audio.arReady(); requestAnimationFrame(readHand); } catch (e) { console.warn("AR initialization failed", e); const code = e?.name || e?.message || "UNKNOWN_ERROR"; const messages = { NotAllowedError: "เบราว์เซอร์ไม่อนุญาตกล้อง: กดไอคอนกล้องข้าง URL แล้วเลือก Allow", NotFoundError: "ไม่พบกล้องในอุปกรณ์นี้", NotReadableError: "กล้องกำลังถูกใช้งานโดยโปรแกรมอื่น", SECURE_CONTEXT_REQUIRED: "ต้องเปิดผ่าน http://localhost หรือ HTTPS", MEDIAPIPE_BUNDLE_UNAVAILABLE: "โหลด MediaPipe ไม่สำเร็จ: ตรวจสอบอินเทอร์เน็ตและ CDN", SCRIPT_LOAD_FAILED: "โหลดไฟล์ MediaPipe CDN ไม่สำเร็จ: ตรวจสอบอินเทอร์เน็ตและรีเฟรช" }; const key = code.startsWith("SCRIPT_LOAD_FAILED") ? "SCRIPT_LOAD_FAILED" : code; arError.value = messages[key] || `AR error: ${code}`; game.value && (game.value.toast = "ใช้การแตะหน้าจอแทน AR ได้เลย", game.value.toastUntil = Date.now() + 2600); stopAR(false); } }
  function readHand(time) { if (!arOn.value || !cameraState.landmarker || !cameraVideo.value || cameraState.busy) return requestAnimationFrame(readHand); cameraState.busy = true; try { const result = cameraState.landmarker.detectForVideo(cameraVideo.value, time); const tip = result.landmarks?.[0]?.[8]; if (tip) { pointer.value = new Vector2((1 - tip.x) * 960, tip.y * 600); const hit = game.value?.items.filter(item => item.hitTest(pointer.value)).sort((a, b) => b.position.y - a.position.y)[0]; if (hit) { if (cameraState.hoverId !== hit.letter.id) { cameraState.hoverId = hit.letter.id; cameraState.hoverStartedAt = performance.now(); cameraState.hoverSelected = false; } else if (!cameraState.hoverSelected && performance.now() - cameraState.hoverStartedAt >= 500) { game.value?.select(pointer.value); cameraState.hoverSelected = true; } } else { cameraState.hoverId = null; cameraState.hoverStartedAt = 0; cameraState.hoverSelected = false; } } else { cameraState.hoverId = null; cameraState.hoverStartedAt = 0; cameraState.hoverSelected = false; } } catch (e) {} cameraState.busy = false; requestAnimationFrame(readHand); }
  function stopAR(clearMessage = true) { arOn.value = false; cameraState.landmarker?.close?.(); cameraState.landmarker = null; cameraState.stream?.getTracks().forEach(t => t.stop()); cameraState.stream = null; if (cameraVideo.value) cameraVideo.value.srcObject = null; cameraState.hoverId = null; cameraState.hoverStartedAt = 0; cameraState.hoverSelected = false; if (clearMessage) arError.value = ""; }
  onMounted(async () => { audio.setMusicVolume(musicVolume.value); window.speechSynthesis?.cancel(); window.scrollTo({ top: 0, left: 0, behavior: "instant" }); const [letterData, spriteData] = await Promise.all([loadJson("data/letters.json"), loadJson("data/sprites.json")]); letters.value = letterData.letters.map(letter => ({ ...letter, thaiClass: consonantClass(letter.char) })); sprites.value = spriteData; assets.letters.onload = () => { assets.letters = removeGreenBackground(assets.letters); }; assets.letters.src = new URL(spriteData.sheets.letters.image, ASSET_ROOT).href; assets.background.src = new URL(spriteData.assets.background, ASSET_ROOT).href; assets.foreground.src = new URL(spriteData.assets.foreground, ASSET_ROOT).href; assets.magicRing.src = new URL(spriteData.assets.magicRing, ASSET_ROOT).href; });
  const targetMatches = letter => settings.category === "all" || letter.thaiClass === settings.category;
  const currentPool = () => settings.category === "all" ? [...letters.value, ...NON_MIDDLE_CONSONANTS] : selectedPool();
  function saveSettings() { localStorage.setItem("middle-class-category", settings.category); localStorage.setItem("middle-class-time", String(settings.time)); localStorage.setItem("middle-class-hearts", String(settings.hearts)); localStorage.setItem("middle-class-mushrooms", String(settings.mushrooms)); localStorage.setItem("middle-class-difficulty", settings.difficulty); localStorage.setItem("middle-class-reduced-motion", String(settings.reducedMotion)); document.documentElement.classList.toggle("reduce-motion", settings.reducedMotion); settingsOpen.value = false; if (screen.value === "game" && game.value) { game.value.stop(); lives.value = settings.hearts; combo.value = 0; startWave(); } }
  function chooseTarget() { const availableItems = game.value?.items.filter(item => !item.collected && targetMatches(item.letter)) || []; if (!availableItems.length) return; const selectedItem = availableItems[Math.floor(Math.random() * availableItems.length)]; target.value = selectedItem.letter; game.value.setTarget(target.value.char); heroState.value = "wave"; audio.target(); }
  function startWave() { if (!game.value || sessionTime.value <= 0) return; waveNumber.value++; waveMiddleCollected.value = 0; const maxMushrooms = settings.difficulty === "easy" ? Math.min(settings.mushrooms, 7) : settings.difficulty === "hard" ? Math.max(settings.mushrooms, 10) : settings.mushrooms; game.value.start(currentPool(), target.value.char, maxMushrooms, settings.category); waveMiddleTotal.value = game.value.items.filter(item => targetMatches(item.letter)).length; game.value.toast = `ชุดที่ ${waveNumber.value} เริ่มแล้ว!`; game.value.toastUntil = Date.now() + 1500; chooseTarget(); }
  function finishWave() { game.value.completed = true; waveCleared.value++; combo.value++; bestCombo.value = Math.max(bestCombo.value, combo.value); const bonus = 25 + Math.min(combo.value, 5) * 5; score.value += bonus; localStorage.setItem("middle-class-score", score.value); game.value.toast = `เคลียร์ชุดที่ ${waveNumber.value}! โบนัส +${bonus}`; game.value.toastUntil = Date.now() + 1800; heroState.value = "excited"; waveTimer = window.setTimeout(() => { waveTimer = null; startWave(); }, 900); }
  function handleCorrect(item) { collected.value++; waveMiddleCollected.value++; combo.value++; bestCombo.value = Math.max(bestCombo.value, combo.value); score.value += 10 + Math.min(combo.value - 1, 4) * 2; if (item.letter.thaiClass === "middle") unlockLetter(item.letter); localStorage.setItem("middle-class-score", score.value); heroState.value = "cheer"; audio.correct(); audio.collect(); audio.magic(); const remaining = game.value?.items.filter(gameItem => !gameItem.collected && targetMatches(gameItem.letter)).length || 0; if (remaining === 0) finishWave(); else window.setTimeout(chooseTarget, 450); }
  function handleWrong() { mistakes.value++; lives.value--; combo.value = 0; heroState.value = "sad"; audio.wrong(); if (lives.value <= 0) window.setTimeout(() => { lives.value = settings.hearts; waveMiddleCollected.value = 0; startWave(); heroState.value = "idle"; }, 1200); }
  async function startGame(levelIndex = activeLevelIndex.value) { if (!letters.value.length) { const letterData = await loadJson("data/letters.json"); letters.value = letterData.letters.map(letter => ({ ...letter, thaiClass: consonantClass(letter.char) })); } setLevel(levelIndex); clearSessionTimers(); screen.value = "game"; lives.value = settings.hearts; mistakes.value = 0; roundStars.value = 0; score.value = 0; collected.value = 0; sessionTime.value = settings.time; waveNumber.value = 0; waveCleared.value = 0; waveMiddleTotal.value = 0; waveMiddleCollected.value = 0; combo.value = 0; bestCombo.value = 0; heroState.value = "wave"; audio.startMusic(); audio.start(); await nextTick(); if (!gameCanvas.value || !sprites.value) return; game.value?.stop(); game.value = new GardenGame(gameCanvas.value, { letters: assets.letters, background: assets.background, foreground: assets.foreground, magicRing: assets.magicRing, meta: sprites.value.sheets.letters }, { correct: handleCorrect, wrong: handleWrong }); startWave(); sessionTimer = window.setInterval(() => { if (sessionTime.value <= 1) { sessionTime.value = 0; finishSession(); } else sessionTime.value--; }, 1000); }
  onMounted(async () => { const levelData = await loadJson("data/levels.json"); levels.value = levelData.levels || []; progression.value.highestLevel = Math.min(progression.value.highestLevel, Math.max(0, levels.value.length - 1)); });
  onBeforeUnmount(() => { clearSessionTimers(); game.value?.stop(); audio.stopMusic(); stopAR(); });
  return { screen, showCollection, settingsOpen, settings, saveSettings, categoryLabel, categoryMission, displayLetters, soundOn, musicVolume, arOn, arError, score, lives, letters, levelLetters, target, collected, progress, levelProgress, timerProgress, sessionTime, waveNumber, waveCleared, waveMiddleTotal, waveMiddleCollected, combo, bestCombo, progression, unlockedCount, levels, activeLevel, activeLevelIndex, levelUnlocked, roundStars, isLetterUnlocked, game, gameCanvas, cameraVideo, pointerStyle, heroSpriteStyle, heroGuideStyle, startGame, nextLevel, goHome, toggleSound, setMusicVolume, toggleAR, onPointerMove, onPointerDown };
} });
app.mount("#app");
